services:
  directus:
    image: directus/directus:latest
    container_name: directus
    restart: unless-stopped
    ports:
      - "8200:8055"
    networks:
      - agrosavia-network
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: pg
      DB_HOST: ${SUPABASE_HOST}
      DB_PORT: 5432
      DB_DATABASE: ${SUPABASE_DB_NAME}
      DB_USER: ${SUPABASE_DB_USER}
      DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
      DB_SSL: 'false'
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    env_file:
      - .env

networks:
  agrosavia-network:
    external: true
